"""
Render og-image.png (1200x630) for social share cards.

Plots every repair centroid from data.bin in the mayor palette on near-black,
so the share card is the actual dataset — the street grid emerges from the
dots alone. Run after preprocess.py if the data changes meaningfully;
the image is a committed artifact, not regenerated by CI.
"""

import struct
from pathlib import Path

import numpy as np
from PIL import Image, ImageDraw, ImageFont

HERE = Path(__file__).resolve().parent
W, H = 1200, 630
BG = (10, 10, 10)

MAYOR_COLORS = [
    (246, 193, 119),  # Bloomberg
    (136, 197, 203),  # de Blasio
    (201, 160, 220),  # Adams
    (130, 224, 143),  # Mamdani
]

raw = (HERE / "data.bin").read_bytes()
N = struct.unpack_from("<I", raw, 0)[0]
off = 4
boro = np.frombuffer(raw, dtype=np.uint8, count=N, offset=off); off += N
mayor = np.frombuffer(raw, dtype=np.uint8, count=N, offset=off); off += N
off += (-off) % 4
month = np.frombuffer(raw, dtype=np.uint16, count=N, offset=off); off += N * 2
off += (-off) % 4
coords = np.frombuffer(raw, dtype=np.float32, count=N * 2, offset=off).reshape(N, 2)

lon, lat = coords[:, 0].astype(np.float64), coords[:, 1].astype(np.float64)

# Equirectangular projection with latitude aspect correction, fit to canvas.
KY = 1.0 / np.cos(np.deg2rad(40.7))
x, y = lon, lat * KY
pad = 30
sx = (W - 2 * pad) / (x.max() - x.min())
sy = (H - 2 * pad) / (y.max() - y.min())
s = min(sx, sy)
px = ((x - x.min()) * s + (W - (x.max() - x.min()) * s) / 2).astype(np.int32)
py = (H - ((y - y.min()) * s + (H - (y.max() - y.min()) * s) / 2)).astype(np.int32)

# Per-pixel counts per mayor; hue = dominant era, brightness = total density.
# Pure additive blending washes to white wherever eras overlap (which is
# every street); argmax keeps the palette saturated.
counts = np.zeros((4, H * W), dtype=np.float32)
for dx in (0, 1):
    for dy in (0, 1):
        qx = np.clip(px + dx, 0, W - 1)
        qy = np.clip(py + dy, 0, H - 1)
        flat = qy.astype(np.int64) * W + qx
        for k in range(4):
            sel = mayor == k
            np.add.at(counts[k], flat[sel], 1.0)

total = counts.sum(axis=0)
dominant = counts.argmax(axis=0)
brightness = np.clip(total * 0.10, 0, 1) ** 0.55
palette = np.array(MAYOR_COLORS, dtype=np.float32)
img_arr = palette[dominant] * brightness[:, None]
img_arr = np.maximum(img_arr, np.array(BG, dtype=np.float32)).reshape(H, W, 3)
img = Image.fromarray(img_arr.astype(np.uint8))

# Title block, NYT-ish: big serif over a soft dark gradient at the bottom.
overlay = Image.new("RGBA", (W, H), (0, 0, 0, 0))
od = ImageDraw.Draw(overlay)
for i in range(220):
    a = int(200 * (i / 220) ** 1.5)
    od.line([(0, H - 220 + i), (W, H - 220 + i)], fill=(5, 5, 5, a))
img = Image.alpha_composite(img.convert("RGBA"), overlay)

d = ImageDraw.Draw(img)
title_font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Georgia Bold.ttf", 64)
sub_font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Georgia.ttf", 26)
d.text((46, H - 150), "The Pothole Map", font=title_font, fill=(239, 239, 239))
d.text((48, H - 64), "400,000 NYC street repairs, animated across four mayors · 2010–2026",
       font=sub_font, fill=(150, 150, 150))

img.convert("RGB").save(HERE / "og-image.png", optimize=True)
print(f"Wrote og-image.png ({(HERE / 'og-image.png').stat().st_size / 1024:.0f} KB)")
